### ISSUE TITLE
Add support for HTML horisontal line in calltree to show fuzz blockers

### ISSUE THREAD

**Issue by DavidKorczynski** [ossf/fuzz-introspector#110]
https://github.com/ossf/fuzz-introspector/issues/74#issuecomment-1070805042

**Comment by AdamKorcz** [comment]
We are lacking a precise definition of a fuzz blocker. The closest I have found is: "A fuzz blocker is a callsite that has most non-covered (red) nodes in front of it." https://github.com/ossf/fuzz-introspector/issues/74#issuecomment-1069724709. This definition is only partly true, as a fuzz-blocker is a part of the code that the fuzzer cannot access without changes to either the fuzzer or the target application. 

For example, not all chunks of red nodes in the calltree are uncovered because of a fuzz-blocker. If a fuzzer has not been running for long, for example, then telling the user that some parts of the target application are not hit because of a fuzz-blocker might be untrue.

Also, considering the user experience, a priority of fuzz-blockers may also be necessary. If we are to show users where there are fuzz blockers in the call tree, then obviously fuzz blockers with 200 nodes are much more important than an uncovered blocks of 3 nodes. 

It may sound trivial, however, without a precise definition of a fuzz-blocker, adding lines to the calltree based simply on how many nodes are red will not be correct in every instance and thus be a source of noise for the user.

If we were to accept that we might be wrong in reporting fuzz-blockers to the user, then I think we should make it very easy for the user to distinguish between a fuzz-blocker and code that the fuzzer can reach but simply hasn't yet. A link to the exact location might be enough for developers, but even so, if the user has to click 20 links and only 10 are actual fuzz-blockers, then we might not be doing them a favour.
