### ISSUE TITLE
/api/far-reach-but-low-coverage missing spaces for types in function names (C++)

### ISSUE THREAD

**Issue by oliverchang** [ossf/fuzz-introspector#1165]
e.g. from https://introspector.oss-fuzz.com/api/far-reach-but-low-coverage?project=jsoncpp

```
"function-name":"Json::Value::removeIndex(unsignedint,Json::Value*)
"function-name":"Json::Reader::parse(charconst*,charconst*,Json::Value&,bool)"
```

There should be spaces between char, const, unsigned etc.

**Comment by DavidKorczynski** [comment]
The reason this happens is because the function names in C++ are in fact mangled C++ names and during the processing we (1) demangle the function name and (2) normalise it by e.g. removing whitespace.

To deal with this we should keep the mangled version of the function name.

FWIW this only happens in C++ because of function name mangling. It doesn't happen in C because arg types and arg names are not part of the function name.

**Comment by DavidKorczynski** [comment]
The `far-reach-but-low-coverage` API now has a field `raw_function_name` which keeps the original, raw, (e.g. mangled c++ names) function names.

For further details we added a JSON schema definition here: https://introspector.oss-fuzz.com/api#api-far-reach-but-low-coverage
