### ISSUE TITLE
Standardize High level conclusions

### ISSUE THREAD

**Issue by Navidem** [ossf/fuzz-introspector#352]
We need to standardize the high level conclusions interpretations.
https://github.com/ossf/fuzz-introspector/blob/c014da178c91dbd5368f680d71291e7fcef3fc17/post-processing/fuzz_html.py#L409-L440

For example the following is the conclusion for `arduinojson` where 69% (complexity reach) is interpreted as okay, while a 68% (function reach) is interpreted as good.

<img width="827" alt="image" src="https://user-images.githubusercontent.com/19780488/176059291-a8d7ba89-f745-431b-98f7-bbd9ed0e276e.png">

We may expose the percentage breakdown table via a hovering box, and/or explain the judgement on what it means "Okay", "good", etc.

**Comment by DavidKorczynski** [comment]
see also https://github.com/ossf/fuzz-introspector/issues/46#issuecomment-1075820294 as we left the original issue on conclusions open for further refinement. @AdamKorcz is currently working on some revamping of the UI and one of the items is adding drop-down to the conclusions which contains further explanations on the given conclusion.

**Comment by DavidKorczynski** [comment]
In https://github.com/ossf/fuzz-introspector/pull/416 I refined the conclusions. This includes removal of descriptions e.g. "This is okay" and "This is good", and a consequence of that is the conclusions will be standardized since the "severity" is now entirely determined by the coloring, which uses the same scale for all conclusions.

**Comment by DavidKorczynski** [comment]
Closed by https://github.com/ossf/fuzz-introspector/pull/416
