### ISSUE TITLE
Improve granularity of fuzz blockers on the UI

### ISSUE THREAD

**Issue by oliverchang** [ossf/fuzz-introspector#418]
e.g. https://storage.googleapis.com/oss-fuzz-introspector/e2fsprogs/inspector-report/20220727/calltree_view_0.html?scrollToNode=00185

![image](https://user-images.githubusercontent.com/759062/181384892-d348d002-5b30-4770-b65d-c4206ef963fc.png)

It's not clear why `ext2fs_free_mem` is reported as the top blocker here. @DavidKorczynski @AdamKorcz could you please take a look?

I believe @Navidem's work on branch blockers would also help here for C/C++.

**Comment by DavidKorczynski** [comment]
The callsite 185 is reported as the blocker, i.e. not the function ext2fs_free_mem. This is because callsite 185 is the last covered callsite before a long sequence of uncovered callsite.

There are a number of things that can be refine in the existing definition and many of which are not super big. See here for reference https://github.com/ossf/fuzz-introspector/issues/254 I held back as requested in the issue, but may do some quick fixing tomorrow while the branch blockers are maturing.

**Comment by Navidem** [comment]
Thanks @oliverchang for pointing this out, these will be tackled with branch blocker (for C/C++).

For python, we may employ a more conservative blocker detection (based on what we have by processing call-graph coverage): employ call_depth to avoid discrepancies like the one reported, i.e. if the next function in the list is not a callee (an incremented call_depth), do not proceed to detect blocker.

**Comment by DavidKorczynski** [comment]
> employ call_depth to avoid discrepancies like the one reported, i.e. if the next function in the list is not a callee (an incremented call_depth), do not proceed to detect blocker.

This used to be in the existing implementation but I removed it because it because it is not required for the next to be a callee. The concept is that it can certainly be some code around the callsite 185 that causes the blocking to happen.

**Comment by DavidKorczynski** [comment]
> There are a number of things that can be refine in the existing definition and many of which are not super big. See here for reference #254 I held back as requested in the issue, but may do some quick fixing tomorrow while the branch blockers are maturing.

I actually think the only bit mentioned in that issue is what I would change, i.e. the effect of that would be the blocker between 181 and 182 in the above picture would not be identified as a blocker because it blocks too few callsites. I don't think this is any urgent thought so will not do any changes on it.

**Comment by oliverchang** [comment]
Thanks for explaining @DavidKorczynski.

As is this is pretty confusing -- could we at least annotate such cases to make this more clear? 

@Navidem your branch profiling work might help provide a lot more clarity on these cases. 

i.e. The real blocker here is the if statement here:

https://storage.googleapis.com/oss-fuzz-coverage/e2fsprogs/reports-by-target/20220727/ext2fs_read_bitmap_fuzzer/linux/src/fuzz/ext2fs_read_bitmap_fuzzer.cc.html#L51

And having the blocker link to that specific location would provide a lot more clarity to users.

@DavidKorczynski @Navidem what would it take to support branch level blocker detection for Python and other languages?

**Comment by Navidem** [comment]
> what would it take to support branch level blocker detection for Python and other languages?

From branch profile perspective, we need reliable intraprocedural CFG and interprocedural call-graph extracted.

**Comment by DavidKorczynski** [comment]
I think it would be ideal if the branch blockers capture that if-statement. It will clear up a lot of easy-to-misunderstand scenarios if a blocker is identified as a specific location in the code, rather than the current definition of "in-between two callsites". Naturally, the blocker will still exist as somewhere between two callsites, so I think we can adopt a lot of the existing UI. For example:
- Making the purple horisontal line a link to the blocker
- Remove the attachment to "call site 185" as where the blocker is, but rather specify e.g. 185/186
- Specify clearly in the UI which function the blocker exists in
- Don't highlight the callsite when using navigation to reach the blocker, but rather highlight the purple line.
