### ISSUE TITLE
Map fuzzer names to output binary names in OSS-Fuzz

### ISSUE THREAD

**Issue by oliverchang** [ossf/fuzz-introspector#44]
Current fuzz introspector reports seem to key fuzzers by the filename where the fuzzer is defined (e.g. https://oss-fuzz-introspector.storage.googleapis.com/zstd/inspector-report/20220220/fuzz_report.html#Fuzzer:-sequence_compression_api.c)

For closer integration with OSS-Fuzz and ClusterFuzz though, we'd like to be able to better map the binary names we see on OSS-Fuzz to these reports. @DavidKorczynski @AdamKorcz WDYT? Would it be possible to include the actual binary names in these reports and key on that instead?

@Navidem FYI

**Comment by DavidKorczynski** [comment]
This was the original goal and I think it would be the nicest to correlate with binaries. However, it's a bit more tricky than initially thought. 

I left a comment in the code discussing this problem: https://github.com/ossf/fuzz-introspector/blob/9497e29c9adb7b843790b74eff44b7a63ec52cfe/post-processing/fuzz_cov_load.py#L45-L48 

There are two problems. The first is that some projects rename the binary files after compilation, which means we can't rely on output names, and the second problem is that we don't always have the right output filename in our linking pass, e.g. the out file will be `ld-temp.o`. 

One way to solve this is to tag the binaries and then use these tags to correlate binaries with fuzz-introspector reports. Will check if this works reliably.

**Comment by DavidKorczynski** [comment]
First take on this is now working:

![Screenshot from 2022-02-23 00-00-27](https://user-images.githubusercontent.com/657617/155240410-4cd99e74-50b3-481c-a84d-9d8702237912.png)


There is some more work in propagating the use of the binary file out throughout the analysis, so will leave the issue open as that is done.

The solution was to add a global variable to the module handled by the compiler pass of fuzz-introspector. This global varialbe is a string that corresponds to the report output by the compiler pass. We can then correlate the compiler reports with executables by looking at the strings of the file, which overcomes both of the challenges I highlight above.

**Comment by MarcoFalke** [comment]
Just as a "warning" that it may be difficult to create a 1-1 mapping of fuzz executable to fuzz filename for every project. For example `bitcoin-core` may place several fuzz targets into one cpp file, if they are related. [process_message.cpp](https://github.com/bitcoin/bitcoin/blob/c44e734dca64a15fae92255a5d848c04adaad2fa/src/test/fuzz/process_message.cpp#L138) contains about 30 fuzz tagets, whose executables will be named `process_message_$msg_name`.

**Comment by DavidKorczynski** [comment]
The 1-1 mapping is between a call to the linker and an executable, not executable and source filename. This should be fine also in the case you mention?

**Comment by MarcoFalke** [comment]
We only call the linker once to create an executable and then use a binary text editor to inject the fuzz target name. (Text replace is faster than calling the linker 300 times).

**Comment by DavidKorczynski** [comment]
Ah interesting. Hmmm. I will have to think about this specific case then. In this example there is not a lot we can do at the moment: other parts, e.g. the CFG extraction, of fuzz-introspector will break because of this. 

One thing I am thinking of doing is adding capabilities for using data from runtime coverage collection as input to the analysis part of fuzz-introspector, e.g. the CFG extraction. This might come in handy here. The current starting point of the analysis really happens at the linking stage right now, and in order to reliably handle your case we should also add the final executable as some form of starting point for the analysis -- coverage data seems to be the most suitable for that.

**Comment by MarcoFalke** [comment]
Ah, it should be easy to use the linker again, if it is needed for introspector. It just means that OSS-Fuzz will take 20 or so minutes longer compiling. I'll play a bit with this and probably revert to using the linker again.

**Comment by DavidKorczynski** [comment]
Closing this as this is now in place:

![Screenshot from 2022-02-25 14-48-20](https://user-images.githubusercontent.com/657617/155735458-aade06e0-70b5-42a5-9e29-e0156c5dd2c0.png)

Please open an issue on specific projects if it's not working on them, but I think the current solution should be working for the vast majority of set ups.

@MarcoFalke I think the conclusion is supporting analysis of Fuzzers where they are patched after linking stage is not the focus atm, so if we can switch the bitcoin-core set up to do all of the linking rather than patching it *should* be supported. Will handle the other issues related to bitcoin separate from this issue.

**Comment by MarcoFalke** [comment]
Thanks, I fully agree that should be no priority or focus on supporting after-link-patching. We only did this as a speedup-hack, because it was simple and had no downsides at the time.

**Comment by DavidKorczynski** [comment]
Sounds good -- it's also a neat hack tbh.
