### ISSUE TITLE
OSS_Fuzz prefix in function names

### ISSUE THREAD

**Issue by thuanpv** [ossf/fuzz-introspector#551]
Hi,

This is not an issue. I am just curious to know what are the differences between functions with and without the "OSS_Fuzz" prefix.

I copy here a subset of the function names shown on the report https://storage.googleapis.com/oss-fuzz-introspector/libpng/inspector-report/20221018/fuzz_report.html.

![Screen Shot 2022-10-19 at 11 53 07 am](https://user-images.githubusercontent.com/3669460/196572622-508a4181-8ba6-4472-9789-1cd890a61686.png)

Thanks in advance for your explanation.

Thuan

**Comment by DavidKorczynski** [comment]
It's because libpng prefixes their function names when building under OSS-Fuzz, which is where the fuzz-introspector analysis extracted the function names from. I think the reason the name is not shown in the coverage report with the prefix is due to how llvm coverage visualisation works, e.g. the source code in the html is not made from data from the compilation (i.e. the prefixed code) but the files on disk themselves.

In code it's due to this line in the libpng: https://github.com/glennrp/libpng/blob/e56f79c0c6d94f5d727fc147d4487038e188cdf2/contrib/oss-fuzz/build.sh#L36

**Comment by thuanpv** [comment]
Thanks for your detailed explanation!
