### ISSUE TITLE
FILES_TO_AVOID is broken

### ISSUE THREAD

**Issue by jvoisin** [ossf/fuzz-introspector#580]
`FILES_TO_AVOID` is used by [libarchive in oss-fuzz](https://github.com/google/oss-fuzz/blob/master/projects/libarchive/build.sh) to mask libxml2, yet it still shows up in the [coverage report]( https://storage.googleapis.com/oss-fuzz-coverage/libarchive/reports/20221101/linux/src/report.html).

**Comment by DavidKorczynski** [comment]
This is because we do not touch the coverage reports as such, but only apply the FILES_TO_AVOID in the fuzz-intospector statically extracted data and the portal. The libxml functions are not showing up in the fuzz-introspector portal, e.g. which is used to do in the past, e.g. see project functions table:
https://storage.googleapis.com/oss-fuzz-introspector/libarchive/inspector-report/20220302/fuzz_report.html
vs
https://storage.googleapis.com/oss-fuzz-introspector/libarchive/inspector-report/20221102/fuzz_report.html

I think it would be nice to offer the option of reduced coverage reports. But may be sitting a bit on the fence as an easier option is to ask the user to avoid compiling libxml with coverage intrumentation flags in oss-fuzz. This should be straightforward for e.g. third-party libraries.

**Comment by jvoisin** [comment]
If we go for the latter, it should be documented somewhere then :)

**Comment by DavidKorczynski** [comment]
Agreed. We could also add some checking for whether the coverage report has data that does not exist within the fuzz-introspector portal and highlight in the portal if this is the case.

**Comment by DavidKorczynski** [comment]
Am not sure what my view is yet though. At first, it seems like fuzz-introspector could introduce some logic for reading .profdata/raw files and do the .html conversion, and then filter the data in the process. However, I am not too convinced the logic of extracting coverage correctly should exist in fuzz-introspector in order to avoid having too many constraints on the build/run environment.

Another option is to document the situation as is now, and then perhaps add some logic in OSS-Fuzz that reads the fuzz-introspector config file during coverage runs and filters the functions accordingly. This would perhaps add another metric (fuzz-introspector coverage builds vs regular coverage builds) which may be a bit too much overhead. In the given instance, e.g. libarchive, would you prefer to have both coverage bulids (The stripped fuzz-introspector one and the non-stripped one)?

**Comment by jvoisin** [comment]
I don't care about the non-striped coverage: libxml2 is already fuzzed somewhere else.

**Comment by jvoisin** [comment]
Would it be possible to provide an example for `In order to exclude certain files from the code coverage reports, it's needed to avoid instrumenting these files entirely.` ?

**Comment by DavidKorczynski** [comment]
> Would it be possible to provide an example for `In order to exclude certain files from the code coverage reports, it's needed to avoid instrumenting these files entirely.` ?

Yes, will give one shortly

**Comment by kleisauke** [comment]
Sorry for replying to an old issue, but for code coverage reports in OSS-Fuzz, I think this can be fixed by adding `coverage_extra_args: -sources src/<PROJECT>` to `project.yaml` , see for example PR:
https://github.com/google/oss-fuzz/pull/12351

For comparison:
https://storage.googleapis.com/oss-fuzz-coverage/libvips/reports/20240815/linux/src/report.html
versus:
https://storage.googleapis.com/oss-fuzz-coverage/libvips/reports/20240816/linux/src/report.html

This way, you can still build dependencies with instrumentation.
