### ISSUE TITLE
Should we always bail if there is a main() in module?

### ISSUE THREAD

**Issue by Navidem** [ossf/fuzz-introspector#66]
Currently if there is a main() function in the module, introspector pass is [skipped](https://github.com/ossf/fuzz-introspector/blob/0e79fb98f0fd1f5cac69c7b38941cafac42b65c1/llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp#L955).

Should this be the case all the time?
There are at least 4 projects on OSS-Fuzz that fuzz introspector does not generate fuzz_report.html because of this check.
Projects include: `tmux, tarantool, libssh, libspectre`

@DavidKorczynski WDYT?

**Comment by DavidKorczynski** [comment]
The reason we do this is because libFuzzer defines its own `main` function https://github.com/llvm/llvm-project/blob/128745cc2681c284bc6d0150a319673a6d6e8424/compiler-rt/lib/fuzzer/FuzzerMain.cpp#L19 -- thus, the idea of skipping is because any binary that already has a `main` function will result in a compilation error when linked to libFuzzer's main function as there will be multiple `main` functions defined.

However:

- I thought libFuzzer would always link in it's own main function after fuzz-introspector pass has run. I am not 100% sure about this though, which means if libFuzzer's main function is in a fuzzer we should analyse the binary.
  - I can do a debugging of the projects you mention to check what happens. The main function that there are in the targets which makes fuzz-introspector skip them, are you sure this is libFuzzer's main function or another one? Do you have links to logs?
- There is an argument not to develop it so closely to libFuzzer's internals, we could provide better support for e.g. AFL++ and honggfuzz targets. I think it makes sense to add this support, although I would prefer to schedule it for a bit later date and first get past the v1 release and having things run smoothly in OSS-Fuzz.  
  - The main problem we really have to overcome in a sense is reliably identifying the "fuzz driver entrypoint". If there is a `main` function and there is an `LLVMFuzzerTestOneInput` function, which is the entrypoint for the fuzz target? We can probably come up with some rules to solve this, but in either case I think this all relates to developing some strong features for "fuzz driver entrypoint" detection.

**Comment by Navidem** [comment]
The overall reasoning makes sense, so the reason that the code currently does not look for `LLVMFuzzerTestOneInput` as the fuzz entry point is that it is libFuzzer specific?

Additionally, looking again into the logs I can see for `tmux` the only fuzz target is `input-fuzzer.c` which introspector pass is skipped because of another main in module when building the target. Here is the log: [tmux-log.txt](https://github.com/ossf/fuzz-introspector/files/8217733/tmux-log.txt)

For the case of `tarantool`, looks like the logic is working just fine. The issue of not having introspector pass is not because of main function detection. More specifically, once building fuzz targets (like `swim_proto_meta_fuzzer`) there is no trace of introspector pass at all without complaining about another main(). Here is log: [tarantool-log.txt](https://github.com/ossf/fuzz-introspector/files/8217776/tarantool-log.txt)

**Comment by DavidKorczynski** [comment]
> so the reason that the code currently does not look for `LLVMFuzzerTestOneInput` as the fuzz entry point is that it is libFuzzer specific?
> 

The code does look for `LLVMFuzzerTestOneInput`: https://github.com/ossf/fuzz-introspector/blob/67c864c3087bc16277a463bdad3d6a1dc5d6ecb9/llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp#L975-L979

The reason we have the `main` check in addition to `LLVMFuzzerTestOneInput` is that some projects will build fuzzers that can be run without using `-fsanitize=fuzzer` by having a `main` function. This is sometimes used by developers to have some form of easy way of reproducing. For example: here is a project that has a wrapper around `LLVMFuzzerTestOneInput` https://github.com/fluent/fluent-bit/blob/master/tests/internal/fuzzers/local_test.c -- this is compiled into executables that are compiled without `-fsanitize=fuzzer`, and this is thus something we are not interesting in from an OSS-Fuzz persective to analyse, since they constitute binaries that won't be on OSS-Fuzz. Thus, including these as samples in the analysis report will end up in a lot of irrelevant data.

The overall question solved by checking for no presence of `main` and presence of `LLVMFuzzerTestOneInput` is that we need an automatic way of choosing which executables to analyse and generate reports for. 

With that said, we have an issue open https://github.com/ossf/fuzz-introspector/issues/6 that may end up exploring using analysis of non-fuzzer binaries.

**Comment by DavidKorczynski** [comment]
> Additionally, looking again into the logs I can see for `tmux` the only fuzz target is `input-fuzzer.c` which introspector pass is skipped because of another main in module when building the target. Here is the log: [tmux-log.txt](https://github.com/ossf/fuzz-introspector/files/8217733/tmux-log.txt)

this one looks quite interesting, will dig into that one

**Comment by DavidKorczynski** [comment]
> The overall question solved by checking for no presence of `main` and presence of `LLVMFuzzerTestOneInput` is that we need an automatic way of choosing which executables to analyse and generate reports for.

another option is to perhaps try and check if `-fsanitize=fuzzer` is provided on the command line. Not sure if this would work

**Comment by DavidKorczynski** [comment]
> another option is to perhaps try and check if `-fsanitize=fuzzer` is provided on the command line. Not sure if this would work

another option is to include a check on whether there is a `main` function and then also checking on whether that `main` function is located inside the file `compiler-rt/lib/fuzzer/FuzzerMain.cpp`

**Comment by DavidKorczynski** [comment]
@Navidem -- I think I have found the issue with `tmux`:
In the following lines `tmux` declares  a weak `main` function when fuzzing. This is why there is a `main` function when compiling the fuzzer, which is highly irregular. 

https://github.com/tmux/tmux/blob/9ed1226a66ee7e097ef858f7bc4b992fbcda2dc7/compat.h#L431-L434

I don't know what I feel about this -- we could put up a guard in the LLVM module that checks some things in the main function to clarify if it's real or not, but I think that may introduce more problems down the line. I may be leaning towards simply saying we will not support this style.

**Comment by Navidem** [comment]
> In the following lines tmux declares main to be weak when fuzzing. This is why there is a main function when compiling the fuzzer, which is highly irregular.

@DavidKorczynski good catch indeed!
Interestingly it seems maintainer added this for oss-fuzz! https://github.com/tmux/tmux/commit/3eb1519bd784076f63fed6678b88f918317a2124

Anyways, I agree we don't need support such rare scenarios atm as we have other blockers to fix.

**Comment by DavidKorczynski** [comment]
> @DavidKorczynski good catch indeed! Interestingly it seems maintainer added this for oss-fuzz! [tmux/tmux@3eb1519](https://github.com/tmux/tmux/commit/3eb1519bd784076f63fed6678b88f918317a2124)
> 
> Anyways, I agree we don't need support such rare scenarios atm as we have other blockers to fix.

Interesting -- I guess they did this in order to avoid changing too much of their build system when integrating fuzzers. Essentially, they can compile in the exact same manner as their regular builds but just link in the fuzzer without having to worry about the existing `main` function. 

Hmm. 

When faced with the `tmux` fuzzer `empty()` (https://llvm.org/doxygen/classllvm_1_1Function.html#a1d8eb3054fd49a89ff41bc22a48f87e7) returns true on the respective LLVM function. Am unsure if we should seek to use that as a heuristic -- the trouble is if there are non-fuzzer binaries that are compiled with `main` functions that also return true from `empty()`which will result in us consider them to be fuzzers.

I think there may be some additional avenues to improve our ability to detect fuzzers without analysing too many binaries. Will have to think a bit about it

**Comment by DavidKorczynski** [comment]
Refined the check to be broader: https://github.com/ossf/fuzz-introspector/commit/31b59f0f381c8e7e63ba9ebb72c43aa45deea47f
