### ISSUE TITLE
Possible incorrect coverage interpretation?

### ISSUE THREAD

**Issue by Navidem** [ossf/fuzz-introspector#74]
Looking into bind9 fuzz [report](https://storage.googleapis.com/oss-fuzz-introspector/bind9/inspector-report/20220310/fuzz_report.html#Fuzzer:-dns_rdata_fromwire_text_fuzzer) for `dns_rdata_fromwire_text_fuzzer`,  I encounter multiple inconsistent/confusing entries in the [calltree](https://storage.googleapis.com/oss-fuzz-introspector/bind9/inspector-report/20220310/calltree_view_1.html):

for example in `calltree idx: 00539`, the callsite [link](https://storage.googleapis.com/oss-fuzz-coverage/bind9/reports/20220310/linux/src/bind9/lib/dns/rdata/generic/opt_41.c.html#L118) shows 352k hits, while the node in call tree is red. 
It is the same for `calltree idx: 00088` with callsite [link](https://storage.googleapis.com/oss-fuzz-coverage/bind9/reports/20220310/linux/src/bind9/lib/dns/callbacks.c.html#L58)

Can it be because the coverage is reporting hits from other fuzz targets? If yes, then #62 can be the solution.

**Comment by DavidKorczynski** [comment]
> Can it be because the coverage is reporting hits from other fuzz targets?

Yes, this is the case. In the calltree we interpret the coverage of an individual fuzzer:
https://github.com/ossf/fuzz-introspector/blob/c62c3fd9dbd5ed41397020c6903b455606d28846/post-processing/fuzz_cov_load.py#L66-L71

However, the coverage report linked to include coverage from all fuzzers

**Comment by Navidem** [comment]
Checking for a project with only one fuzzer (aspell) it seems there is something off:
https://storage.googleapis.com/oss-fuzz-introspector/aspell/inspector-report/20220314/fuzz_report.html#call_tree_0

The top blocker (call_index 760) has 117k hits:
https://storage.googleapis.com/oss-fuzz-coverage/aspell/reports/20220314/linux/src/aspell/lib/config-c.cpp.html#L117

**Comment by DavidKorczynski** [comment]
This should be working now!

**Comment by DavidKorczynski** [comment]
> Checking for a project with only one fuzzer (aspell) it seems there is something off: https://storage.googleapis.com/oss-fuzz-introspector/aspell/inspector-report/20220314/fuzz_report.html#call_tree_0
> 
> The top blocker (call_index 760) has ~27k hits: https://storage.googleapis.com/oss-fuzz-coverage/aspell/reports/20220314/linux/src/aspell/lib/config-c.cpp.html#L117

This should be working now! Improvements have been made both in compiler instrumentation and the post-processing.

**Comment by Navidem** [comment]
Checked [latest](https://storage.googleapis.com/oss-fuzz-introspector/aspell/inspector-report/20220316/fuzz_report.html) `aspell` introspector reports. Fuzzer call tree is noticeably changed, but I still find entries in blocker table that does not make sense to me:

- The top [blocker](https://storage.googleapis.com/oss-fuzz-coverage/aspell/reports/20220316/linux/src/aspell/common/filter.cpp.html#L39) (calltree index 1721) has hitcount of 576 equal to the first statement in the parent function.

- It is the same for second top [blocker](https://storage.googleapis.com/oss-fuzz-coverage/aspell/reports/20220316/linux/src/aspell/common/config.cpp.html#L205). 


It is the same for `leveldb` that I [checked](https://storage.googleapis.com/oss-fuzz-introspector/leveldb/inspector-report/20220316/fuzz_report.html): 
- the top blocker is in `LLVMFuzzerTestOneInput` with thousands of hits.
- [second](https://storage.googleapis.com/oss-fuzz-coverage/leveldb/reports/20220316/linux/src/leveldb/fuzz_db.cc.html#L57) top blocker (call index 9) is at a line with 112k hitcount

Looking into the [calltree](https://storage.googleapis.com/oss-fuzz-introspector/leveldb/inspector-report/20220316/calltree_view_0.html) for `leveldb` it does not make sense how index 9 is hit, but none of its children are not:
<img width="1393" alt="Screen Shot 2022-03-16 at 3 46 12 PM" src="https://user-images.githubusercontent.com/19780488/158703857-7f09601d-e08e-482d-bede-aa9ec2d270fb.png">



P.S: I sort entries in the blocker table based on "Blocked Nodes" column.

**Comment by DavidKorczynski** [comment]
A fuzz blocker is a callsite that has most non-covered (red) nodes in front of it. Thus, it makes sense it's a `green` node -- in that a green will always have more reds forward relative to the first red node. The callsites you highlight has a huge chunk of red callsites in front of them, i.e. a lot of blocked code. Thus, it's correct relative to it's current definition.

we can change the definition to be that a fuzz blocker having to be red itself as well.

One thing about aspell is that the coverage collection does not include coverage data from the red callsites shown, as it's part of `libcxx`. That's probably something we should look into.

it's easy to have a case where a node is green and no forward of them will be red, consider this example.

```
void A(size_t a, size_t b) {
 if (a == b) {
   return;
 }
 ...
 ...
 complex logic.
 ...
 ...
}

int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
  A(size, size);
}
```

In the above the callsite into `A` will be green but everything beneath it will be red. the callsite `A` is defined as the fuzz blocked.

**Comment by oliverchang** [comment]
> A fuzz blocker is a callsite that has most non-covered (red) nodes in front of it. Thus, it makes sense it's a green node -- in that a green will always have more reds forward relative to the first red node. The callsites you highlight has a huge chunk of red callsites in front of them, i.e. a lot of blocked code. Thus, it's correct relative to it's current definition.

Could we perhaps make the blocker a different colour? To make this more prominent / distinct in the calltree? 

We should also add some text somewhere explain exactly what a fuzz blocker is. 

>  Alternatively, we should change the link in the fuzz blocker table to the actual tree, as the tree makes it very obvious what code is hit versus not hit.

+1. I think we should just do this regardless. Longer term I think we'd want a more unified page that contains both the call tree and the coverage report.

> One thing about aspell is that the coverage collection does not include coverage data from the red callsites shown, as it's part of libcxx. However, the code is most definitely run -- but we don't have any data on that. i.e. it seems like the lto build (the call tree build) includes more data than the coverage build. That's probably something we should look into.

Per #107, could we just exclude all libcxx and libc functions here? The most important/useful parts here would be the code being tested, rather than standard library functions (which we're not necessarily aiming to maximise the coverage of).

**Comment by Navidem** [comment]
> it's easy to have a case where a node is green and no forward of them will be red, consider this example.

Thanks David, I guess this is the second time you depicting the scenario! I should say "Parent Function" column was misleading to me, do you have a scenario that having parent name is more useful than the name of the blocked function itself?

I see that the current blocker table is the expected result based on the calltree, but I believe we may need to refine the blocker lists. At least for the cases that I mentioned in this thread I believe standard library functions are being marked as top blockers and causing confusion.  Skipping standard library functions make sense as example if we have a call to `printf` which checks for many specific cases, we don't want it reported as blocker.

In addition to #107 we may need to exclude fuzz engine libraries too:

> the top blocker is in LLVMFuzzerTestOneInput with thousands of hits.

The blocker in this case is ConsumeRandomLengthString() in FuzzedDataProvider.h

**Comment by DavidKorczynski** [comment]
> Could we perhaps make the blocker a different colour? To make this more prominent / distinct in the calltree?

Rather than this I think we should change the concept of a fuzz blocker being one of the nodes in the calltree to a fuzz blocker being an edge, i.e. a transition from one node to the next. That's also how it is in practice, in that the code that blocks the fuzzer exists between two callsites. Thus, we should make the blockers a small horisontal line in the calltree.

**Comment by DavidKorczynski** [comment]
> We should also add some text somewhere explain exactly what a fuzz blocker is.

I think we should handle this with a location for proper documentation, as it's likely we need to have more detailed explanation about many of the concepts in fuzz-introspector. https://github.com/ossf/fuzz-introspector/issues/113

**Comment by DavidKorczynski** [comment]
> I should say "Parent Function" column was misleading to me, do you have a scenario that having parent name is more useful than the name of the blocked function itself?
> 

The parent function is the function in which the callsite exists, which is important to understanding where the blocking occurs? I think in general the view that a fuzz blocker is a node in the tree is not entirely correct and may lead to some confusion, please see the above comment on it being an edge. 

Once we clear up the functions included in the analysis and fix the links in the fuzz blocker table to point to the calltree rather than the coverage report, then it should hopefully be more intuitive. 

> I see that the current blocker table is the expected result based on the calltree, but I believe we may need to refine the blocker lists. At least for the cases that I mentioned in this thread I believe standard library functions are being marked as top blockers and causing confusion. Skipping standard library functions make sense as example if we have a call to `printf` which checks for many specific cases, we don't want it reported as blocker.
> 

Yeah -- although I find this is not so much a question about the definition of fuzz blocker but rather a definition of what functions we include in the analysis of fuzz-introspector. i.e. because there is no coverage data in the std:: library then it mixes it up -- but if there had been coverage data from the std:: library then there would have been no issues? 

In the long term I think we should aim for the ability to allow the user to modify this rather than making too many decisions, because there are many projects in oss-fuzz that build third party libraries but are not particularly interested in them from a fuzz-introspector perspective. They will by and large run into the same issue as this but with different data.

This can be extrapolated on though, and I have written a few words here https://github.com/ossf/fuzz-introspector/issues/107#issuecomment-1071212419

**Comment by Navidem** [comment]
> In the long term I think we should aim for the ability to allow the user to modify this rather than making too many decisions

Exactly! This is something that I had in mind too, the user may want to focus on some submodules of their projects therefore they should be able to control what code be included/excluded in the analysis.

**Comment by oliverchang** [comment]
> > Could we perhaps make the blocker a different colour? To make this more prominent / distinct in the calltree?
> 
> Rather than this I think we should change the concept of a fuzz blocker being one of the nodes in the calltree to a fuzz blocker being an edge, i.e. a transition from one node to the next. That's also how it is in practice, in that the code that blocks the fuzzer exists between two callsites. Thus, I suggest we make the blockers a small horisontal line in the calltree #110.

Thanks! a horizontal line makes a lot of sense :)

**Comment by oliverchang** [comment]
@Navidem any remaining items here to address?
