### ISSUE TITLE
Runtime coverage exceeds total

### ISSUE THREAD

**Issue by jimaf** [ossf/fuzz-introspector#812]
Todays report for libfido2 https://storage.googleapis.com/oss-fuzz-introspector/libfido2/inspector-report/20230207/fuzz_report.html   Shows runtime coverage of 516% of functions.  This seems too high. Says 1991 out of 386 total functions covered.

**Comment by DavidKorczynski** [comment]
Thank you @jimaf -- referencing this issue https://github.com/ossf/fuzz-introspector/issues/795 which is an umbrella for tracking multiple coverage issues. Will look at this shortly!

**Comment by DavidKorczynski** [comment]
The issue has been fixed now: https://storage.googleapis.com/oss-fuzz-introspector/libfido2/inspector-report/20230301/fuzz_report.html

The main issue was that the functions covered at runtime had a different type of upper-bound than the total functions. This was due to some data being interpreted from two different data sources (one the code coverage report and the other being the static analysis report).

However, `libfido` is a bit tricky, because there seems to be a discrepancy between the flags used between the various projects compiled during the building of the fuzzers. For example, the function list includes all functions that are compiled with LLVM LTO during the build https://storage.googleapis.com/oss-fuzz-introspector/libfido2/inspector-report/20230301/fuzz_report.html#Project-functions-overview and this list is much shorter than the code included in the coverage report: https://storage.googleapis.com/oss-fuzz-coverage/libfido2/reports/20230301/linux/report.html

It seems only the code in `/libfido2/fuzz` is compiled and linked with the correct settings for Fuzz Introspector to work.

The settings for Fuzz Introspector are:
- These flags: https://github.com/google/oss-fuzz/blob/9503ea34f5c8b3374f621906768ffadf7d345876/infra/base-images/base-builder/Dockerfile#L73
- Use of the following `ar`, `nm`, and `ranlib` files: https://github.com/google/oss-fuzz/blob/9503ea34f5c8b3374f621906768ffadf7d345876/infra/base-images/base-builder/compile#L170-L177

Could it be that some of the building stages are missing out some of the above (in particular the `-flto` and `-fuse-ld=gold`)?

**Comment by DavidKorczynski** [comment]
This is fixed now: https://storage.googleapis.com/oss-fuzz-introspector/libfido2/inspector-report/20230911/fuzz_report.html
